### ISSUE TITLE
Add steady-state calculator

### ISSUE THREAD

**Issue by ammario** [ammario/grams.io#1]
Per HN feedback

**Comment by alshdavid** [comment]
Perhaps just having the ability to duplicate a line will make it easier for people to calculate their own steady state levels

**Comment by ammario** [comment]
<img width="1042" alt="image" src="https://user-images.githubusercontent.com/7416144/235222971-1d6da05e-19a3-402e-8c03-7350e0ce8fe1.png">
Done in c3b5737f5e59a370d9f3bfb5053a1e1db18e08f0
