### ISSUE TITLE
Large list of doses breaks graph

### ISSUE THREAD

**Issue by alshdavid** [ammario/grams.io#5]
In this [example](https://grams.io/?i=0h-Drug-1-108h&i=48h-Drug-1-108h&i=96h-Drug-1-108h&i=144h-Drug-1-108h&i=192h-Drug-1-108h&i=240h-Drug-1-108h&i=288h-Drug-1-108h&i=336h-Drug-1-108h&i=384h-Drug-1-108h&i=432h-Drug-1-108h&i=480h-Drug-1-108h&i=528h-Drug-1-108h&i=576h-Drug-1-108h&i=624h-Drug-1-108h&i=672h-Drug-1-108h&i=720h-Drug-1-108h&i=768h-Drug-1-108h&i=816h-Drug-1-108h&i=864h-Drug-1-108h&i=912h-Drug-1-108h&i=960h-Drug-1-108h&i=1008h-Drug-1-108h&i=1056h-Drug-1-108h&i=1104h-Drug-1-108h&i=1152h-Drug-1-108h&i=1200h-Drug-1-108h&i=1248h-Drug-1-108h&i=1296h-Drug-1-108h&i=1344h-Drug-1-108h&i=1392h-Drug-1-108h&i=1440h-Drug-1-108h), a large number of doses squash the graph

![image](https://user-images.githubusercontent.com/12656294/234227717-d5cfda2d-acf1-445c-913b-9bb7c8174f72.png)

Maybe put the graph above the drug doses?

**Comment by ammario** [comment]
Would your use case be fixed by the addition of the steady-state calculator?

**Comment by ammario** [comment]
<img width="823" alt="image" src="https://github.com/ammario/grams.io/assets/7416144/14e130b8-fcfb-4dd1-84b0-bc478c13d722">
